name: CI Pipeline

on: 
  push:
    branches:
      - main

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        
      - name: install uv
        uses: astral-sh/setup-uv@v3

      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: install dependencies
        run: |
          uv sync

      - name: run pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MLFLOW_REPO_OWNER: ${{ secrets.MLFLOW_REPO_OWNER }}
          MLFLOW_REPO_NAME: ${{ secrets.MLFLOW_REPO_NAME }}
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          uv run dvc repro
        
      - name: Run model tests
        env:
          MLFLOW_REPO_OWNER: ${{ secrets.MLFLOW_REPO_OWNER }}
          MLFLOW_REPO_NAME: ${{ secrets.MLFLOW_REPO_NAME }}
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          uv run python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        env:
          MLFLOW_REPO_OWNER: ${{ secrets.MLFLOW_REPO_OWNER }}
          MLFLOW_REPO_NAME: ${{ secrets.MLFLOW_REPO_NAME }}
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: uv run python scripts/promote_model.py

      - name: Run flask app tests
        if: success()
        env:
          MLFLOW_REPO_OWNER: ${{ secrets.MLFLOW_REPO_OWNER }}
          MLFLOW_REPO_NAME: ${{ secrets.MLFLOW_REPO_NAME }}
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: uv run python -m unittest tests/test_flask_app.py

      - name: Login to AWS ECR
        if: success()
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION_NAME }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION_NAME }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_NAME }}.amazonaws.com
          
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_NAME }}.amazon.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Check Docker Authentication
        run: docker info

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_NAME }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
