name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        
      - name: install uv
        uses: astral-sh/setup-uv@v3

      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: install dependencies
        run: |
          uv sync

      - name: run pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MLFLOW_REPO_OWNER: ${{ secrets.MLFLOW_REPO_OWNER }}
          MLFLOW_REPO_NAME: ${{ secrets.MLFLOW_REPO_NAME }}
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          uv run dvc repro